"""add remittance models and sequences

Revision ID: 1092cc5b7f20
Revises: 466b9399c474
Create Date: 2026-09-28 17:08:46.048588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1092cc5b7f20'
down_revision = '466b9399c474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance_master',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remittance_no', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('cash_in_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected'), server_default='Pending', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_master_branch_id'), 'remittance_master', ['branch_id'], unique=False)
    op.create_index(op.f('ix_remittance_master_business_date'), 'remittance_master', ['business_date'], unique=False)
    op.create_index(op.f('ix_remittance_master_remittance_no'), 'remittance_master', ['remittance_no'], unique=True)
    op.create_table('remittance_denominations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remittance_id', sa.BigInteger(), nullable=False),
    sa.Column('denomination', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_denominations_remittance_id'), 'remittance_denominations', ['remittance_id'], unique=False)
    op.create_table('remittance_receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remittance_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_receipt_id', sa.Integer(), nullable=False),
    sa.Column('receipt_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fee_receipt_id'], ['fee_payments.payment_id'], ),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_receipts_fee_receipt_id'), 'remittance_receipts', ['fee_receipt_id'], unique=False)
    op.create_index(op.f('ix_remittance_receipts_remittance_id'), 'remittance_receipts', ['remittance_id'], unique=False)
    op.add_column('enrollment_sequences', sa.Column('remittance_prefix', sa.String(length=20), server_default='REM', nullable=False))
    op.add_column('enrollment_sequences', sa.Column('last_remittance_no', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_sequences', 'last_remittance_no')
    op.drop_column('enrollment_sequences', 'remittance_prefix')
    op.drop_index(op.f('ix_remittance_receipts_remittance_id'), table_name='remittance_receipts')
    op.drop_index(op.f('ix_remittance_receipts_fee_receipt_id'), table_name='remittance_receipts')
    op.drop_table('remittance_receipts')
    op.drop_index(op.f('ix_remittance_denominations_remittance_id'), table_name='remittance_denominations')
    op.drop_table('remittance_denominations')
    op.drop_index(op.f('ix_remittance_master_remittance_no'), table_name='remittance_master')
    op.drop_index(op.f('ix_remittance_master_business_date'), table_name='remittance_master')
    op.drop_index(op.f('ix_remittance_master_branch_id'), table_name='remittance_master')
    op.drop_table('remittance_master')
    # ### end Alembic commands ###
