"""revert to aggregated raw punch staging

Revision ID: 117244f476ce
Revises: 1b7fdffc436c
Create Date: 2026-07-02 16:24:07.914359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '117244f476ce'
down_revision = '1b7fdffc436c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_staging', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_staging', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
