"""revert to aggregated raw punch staging

Revision ID: 117244f476ce
Revises: 1b7fdffc436c
Create Date: 2026-07-02 16:24:07.914359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '117244f476ce'
down_revision = '1b7fdffc436c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('first_in', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('last_out', sa.Time(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('punch_mode')
        batch_op.drop_column('punch_time')
        batch_op.drop_column('device_code')
        batch_op.drop_column('verify_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_mode', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('device_code', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('punch_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('punch_mode', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('last_out')
        batch_op.drop_column('first_in')
        batch_op.drop_column('attendance_date')

    # ### end Alembic commands ###
