"""School-wise HR masters

Revision ID: 195a642ab54b
Revises: 1d2565c95a37
Create Date: 2026-06-27 10:25:51.593813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '195a642ab54b'
down_revision = '1d2565c95a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('department_code'))
        batch_op.create_unique_constraint('uq_school_dept_code', ['school_id', 'department_code'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('designation_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('designation_code'))
        batch_op.create_unique_constraint('uq_school_desig_code', ['school_id', 'designation_code'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')


    with op.batch_alter_table('shift_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('shift_code'))
        batch_op.create_unique_constraint('uq_school_shift_code', ['school_id', 'shift_code'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('staff_category_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('category_code'))
        batch_op.create_unique_constraint('uq_school_category_code', ['school_id', 'category_code'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('staff_status_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('status_code'))
        batch_op.create_unique_constraint('uq_school_status_code', ['school_id', 'status_code'])
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_status_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_school_status_code', type_='unique')
        batch_op.create_index(batch_op.f('status_code'), ['status_code'], unique=True)
        batch_op.drop_column('school_id')

    with op.batch_alter_table('staff_category_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_school_category_code', type_='unique')
        batch_op.create_index(batch_op.f('category_code'), ['category_code'], unique=True)
        batch_op.drop_column('school_id')

    with op.batch_alter_table('shift_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_school_shift_code', type_='unique')
        batch_op.create_index(batch_op.f('shift_code'), ['shift_code'], unique=True)
        batch_op.drop_column('school_id')


    with op.batch_alter_table('designation_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_school_desig_code', type_='unique')
        batch_op.create_index(batch_op.f('designation_code'), ['designation_code'], unique=True)
        batch_op.drop_column('school_id')

    with op.batch_alter_table('department_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_school_dept_code', type_='unique')
        batch_op.create_index(batch_op.f('department_code'), ['department_code'], unique=True)
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
