"""add approval_status to petty_cash

Revision ID: 1a91df357c35
Revises: 86b23d3438a5
Create Date: 2026-06-22 11:42:24.857013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a91df357c35'
down_revision = '86b23d3438a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Enum('Pending', 'Approved', 'Rejected'), server_default='Pending', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
