"""Add staff_code, employee_id, and StaffEnrollmentSequence

Revision ID: 1d2565c95a37
Revises: cdda20559d39
Create Date: 2026-06-27 10:14:58.877590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d2565c95a37'
down_revision = 'cdda20559d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_enrollment_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('staff_code_prefix', sa.String(length=20), nullable=False),
    sa.Column('last_staff_no', sa.Integer(), nullable=False),
    sa.Column('employee_id_prefix', sa.String(length=20), nullable=False),
    sa.Column('last_employee_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('last_employee_no >= 0', name='chk_employee_no_positive'),
    sa.CheckConstraint('last_staff_no >= 0', name='chk_staff_no_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department_master.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'department_id', name='uq_branch_dept_staff_sequence')
    )
    with op.batch_alter_table('staff_master', schema=None) as batch_op:
        batch_op.alter_column('employee_code', new_column_name='staff_code', existing_type=sa.String(length=50), existing_nullable=False)
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))
        batch_op.drop_index('employee_code')
        batch_op.create_unique_constraint(batch_op.f('uq_staff_master_staff_code'), ['staff_code'])
        batch_op.create_unique_constraint(batch_op.f('uq_staff_master_employee_id'), ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_master', schema=None) as batch_op:
        batch_op.alter_column('staff_code', new_column_name='employee_code', existing_type=sa.String(length=50), existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_staff_master_staff_code'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_staff_master_employee_id'), type_='unique')
        batch_op.create_unique_constraint('employee_code', ['employee_code'])
        batch_op.drop_column('employee_id')

    op.drop_table('staff_enrollment_sequences')
    # ### end Alembic commands ###
