"""Add is_locked and index to StudentAcademicRecord

Revision ID: 2d216c34a8d6
Revises: bab7d856c7d9
Create Date: 2026-04-10 10:59:11.548123

"""
from alembic import op
import sqlalchemy as sa







 
# revision identifiers, used by Alembic.
revision = '2d216c34a8d6'
down_revision = 'bab7d856c7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('student_academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_student_year', ['student_id', 'academic_year'], unique=False)
        batch_op.create_unique_constraint('uq_student_academic_year', ['student_id', 'academic_year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_academic_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_academic_year', type_='unique')
        batch_op.drop_index('idx_student_year')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
