"""addign unique constratints for attendance staging

Revision ID: 407c67fbaeee
Revises: c54e9ca2846f
Create Date: 2026-07-06 12:15:42.499658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '407c67fbaeee'
down_revision = 'c54e9ca2846f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_staging', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_attendance_stating_employee_date', ['employee_id', 'attendance_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    with op.batch_alter_table('attendance_staging', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attendance_stating_employee_date', type_='unique')

    # ### end Alembic commands ###
