"""Update HR constraints

Revision ID: 583e65499039
Revises: 1e212f5b201b
Create Date: 2026-06-29 11:08:24.735839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
"""Update HR constraints

Revision ID: 583e65499039
Revises: 1e212f5b201b
Create Date: 2026-06-29 11:08:24.735839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '583e65499039'
down_revision = '1e212f5b201b'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    
    # Preflight check for duplicates
    res = conn.execute(sa.text("SELECT staff_id, attendance_date, COUNT(*) FROM attendance_head GROUP BY staff_id, attendance_date HAVING COUNT(*) > 1"))
    if res.fetchone():
        raise ValueError("Duplicate rows found in attendance_head for (staff_id, attendance_date). Please clean up before running this migration.")
        
    res = conn.execute(sa.text("SELECT device_id, biometric_id, COUNT(*) FROM staff_biometric_mapping GROUP BY device_id, biometric_id HAVING COUNT(*) > 1"))
    if res.fetchone():
        raise ValueError("Duplicate rows found in staff_biometric_mapping for (device_id, biometric_id). Please clean up before running this migration.")
        
    res = conn.execute(sa.text("SELECT staff_id, device_id, COUNT(*) FROM staff_biometric_mapping GROUP BY staff_id, device_id HAVING COUNT(*) > 1"))
    if res.fetchone():
        raise ValueError("Duplicate rows found in staff_biometric_mapping for (staff_id, device_id). Please clean up before running this migration.")
        
    res = conn.execute(sa.text("SELECT school_id, employee_id, COUNT(*) FROM staff_master WHERE employee_id IS NOT NULL GROUP BY school_id, employee_id HAVING COUNT(*) > 1"))
    if res.fetchone():
        raise ValueError("Duplicate rows found in staff_master for (school_id, employee_id). Please clean up before running this migration.")
        
    res = conn.execute(sa.text("SELECT school_id, staff_code, COUNT(*) FROM staff_master GROUP BY school_id, staff_code HAVING COUNT(*) > 1"))
    if res.fetchone():
        raise ValueError("Duplicate rows found in staff_master for (school_id, staff_code). Please clean up before running this migration.")

    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(conn)
    
    attendance_head_constraints = [c['name'] for c in inspector.get_unique_constraints('attendance_head')]
    if 'uq_attendance_head_staff_date' not in attendance_head_constraints:
        with op.batch_alter_table('attendance_head', schema=None) as batch_op:
            batch_op.create_unique_constraint('uq_attendance_head_staff_date', ['staff_id', 'attendance_date'])

    biometric_mapping_constraints = [c['name'] for c in inspector.get_unique_constraints('staff_biometric_mapping')]
    with op.batch_alter_table('staff_biometric_mapping', schema=None) as batch_op:
        if 'uq_biometric_mapping_device_biometric' not in biometric_mapping_constraints:
            batch_op.create_unique_constraint('uq_biometric_mapping_device_biometric', ['device_id', 'biometric_id'])
        if 'uq_biometric_mapping_staff_device' not in biometric_mapping_constraints:
            batch_op.create_unique_constraint('uq_biometric_mapping_staff_device', ['staff_id', 'device_id'])

    staff_code_sequences_fks = [fk['name'] for fk in inspector.get_foreign_keys('staff_code_sequences')]
    with op.batch_alter_table('staff_code_sequences', schema=None) as batch_op:
        if 'fk_scs_updated_by' not in staff_code_sequences_fks:
            batch_op.create_foreign_key('fk_scs_updated_by', 'users', ['updated_by'], ['user_id'])
        if 'fk_scs_created_by' not in staff_code_sequences_fks:
            batch_op.create_foreign_key('fk_scs_created_by', 'users', ['created_by'], ['user_id'])

    staff_master_constraints = [c['name'] for c in inspector.get_unique_constraints('staff_master')]
    staff_master_indexes = [i['name'] for i in inspector.get_indexes('staff_master')]
    with op.batch_alter_table('staff_master', schema=None) as batch_op:
        if 'uq_staff_master_employee_id' in staff_master_indexes:
            batch_op.drop_index('uq_staff_master_employee_id')
        elif 'uq_staff_master_employee_id' in staff_master_constraints:
            batch_op.drop_constraint('uq_staff_master_employee_id', type_='unique')
            
        if 'uq_staff_master_staff_code' in staff_master_indexes:
            batch_op.drop_index('uq_staff_master_staff_code')
        elif 'uq_staff_master_staff_code' in staff_master_constraints:
            batch_op.drop_constraint('uq_staff_master_staff_code', type_='unique')
            
        if 'uq_staff_master_school_employee_id' not in staff_master_constraints:
            batch_op.create_unique_constraint('uq_staff_master_school_employee_id', ['school_id', 'employee_id'])
        if 'uq_staff_master_school_staff_code' not in staff_master_constraints:
            batch_op.create_unique_constraint('uq_staff_master_school_staff_code', ['school_id', 'staff_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_master', schema=None) as batch_op:
        batch_op.drop_constraint('uq_staff_master_school_staff_code', type_='unique')
        batch_op.drop_constraint('uq_staff_master_school_employee_id', type_='unique')
        batch_op.create_index('uq_staff_master_staff_code', ['staff_code'], unique=True)
        batch_op.create_index('uq_staff_master_employee_id', ['employee_id'], unique=True)

    with op.batch_alter_table('staff_code_sequences', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scs_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_scs_updated_by', type_='foreignkey')

    with op.batch_alter_table('staff_biometric_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('uq_biometric_mapping_staff_device', type_='unique')
        batch_op.drop_constraint('uq_biometric_mapping_device_biometric', type_='unique')

    with op.batch_alter_table('attendance_head', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attendance_head_staff_date', type_='unique')

    # ### end Alembic commands ###
