"""add school_id and branch_id to subjectmaster

Revision ID: 5b0ab702db53
Revises: 3f7b2a9c1d4e
Create Date: 2026-05-20 10:27:41.036074

"""
# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0ab702db53'
down_revision = '3f7b2a9c1d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjectmaster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjectmaster', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
