"""Added raw_packet and audit fields to BiometricPunchLog

Revision ID: 60cb657c3d8d
Revises: b1825503a71b
Create Date: 2026-06-30 10:27:31.306291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60cb657c3d8d'
down_revision = 'b1825503a71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_punch_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_packet', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('received_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('received_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packet_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ack_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_punch_log', schema=None) as batch_op:
        batch_op.drop_column('processing_error')
        batch_op.drop_column('ack_sent')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('packet_version')
        batch_op.drop_column('received_port')
        batch_op.drop_column('received_ip')
        batch_op.drop_column('raw_packet')
    # ### end Alembic commands ###
