"""Added raw_packet and audit fields to BiometricPunchLog

Revision ID: 60cb657c3d8d
Revises: b1825503a71b
Create Date: 2026-06-30 10:27:31.306291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60cb657c3d8d'
down_revision = 'b1825503a71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
