"""add_school_tenant_and_user_fks

Revision ID: 64c7627cad58
Revises: 2d216c34a8d6
Create Date: 2026-05-04 10:47:18.012536

"""
# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c7627cad58'
down_revision = '2d216c34a8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=False),
    sa.Column('school_code', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('domain_name', sa.String(length=150), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    op.drop_table('schools')
    # ### end Alembic commands ###
