"""update enum hifz to deeniyath

Revision ID: 6a53ec797765
Revises: af6528073d91
Create Date: 2026-05-26 11:23:06.897757

"""
# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a53ec797765'
down_revision = 'af6528073d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjectmaster', schema=None) as batch_op:
        batch_op.alter_column('subject_type',
               existing_type=mysql.ENUM('Hifz', 'Academic'),
               type_=sa.Enum('Deeniyath', 'Academic'),
               existing_nullable=True)
    with op.batch_alter_table('students',schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_no',sa.String(),nullable = True))
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheque_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cheque_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjectmaster', schema=None) as batch_op:
        batch_op.alter_column('subject_type',
               existing_type=sa.Enum('Deeniyath', 'Academic'),
               type_=mysql.ENUM('Hifz', 'Academic'),
               existing_nullable=True)
    with op.batch_alter_table('students',schema=None) as batch_op:
        batch_op.drop_column('enrollment_no')
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_column('cheque_date')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('cheque_no')


    # ### end Alembic commands ###
