"""adding staff salary account and document

Revision ID: 6e5d43b50d1c
Revises: eaf76f101918
Create Date: 2026-09-09 14:32:54.008141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e5d43b50d1c'
down_revision = 'eaf76f101918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_account_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=150), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('branch_name', sa.String(length=150), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('pf_applicable', sa.Boolean(), nullable=True),
    sa.Column('pf_number', sa.String(length=50), nullable=True),
    sa.Column('esi_applicable', sa.Boolean(), nullable=True),
    sa.Column('esi_number', sa.String(length=50), nullable=True),
    sa.Column('pt_applicable', sa.Boolean(), nullable=True),
    sa.Column('tds_applicable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('staff_document_type_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('allowed_extensions', sa.String(length=100), nullable=True),
    sa.Column('max_file_size', sa.Integer(), nullable=True),
    sa.Column('requires_expiry', sa.Boolean(), nullable=True),
    sa.Column('requires_document_number', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('staff_salary_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('salary_type', sa.String(length=50), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_structure_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('payroll_status', sa.String(length=50), nullable=True),
    sa.Column('gratuity_applicable', sa.Boolean(), nullable=True),
    sa.Column('bonus_applicable', sa.Boolean(), nullable=True),
    sa.Column('overtime_applicable', sa.Boolean(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('payroll_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('staff_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issued_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['staff_document_type_master.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_documents')
    op.drop_table('staff_salary_details')
    op.drop_table('staff_document_type_master')
    op.drop_table('staff_account_details')
    # ### end Alembic commands ###
