"""adding user email

Revision ID: 800c9d6eaf63
Revises: b62d6696f78a
Create Date: 2026-03-11 13:07:55.951565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800c9d6eaf63'
down_revision = 'b62d6696f78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_module')
    
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('useremail', sa.String(length=100), nullable=True))

        batch_op.alter_column(
            'password',
            existing_type=sa.String(length=50),
            type_=sa.String(length=255),
            existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_module', ['module'], unique=False)
    
    with op.batch_alter_table('users') as batch_op:
        # NOTE: Not reverting password column from 255 to 50 as that would
        # truncate modern password hashes (bcrypt/scrypt) and break logins.

        batch_op.drop_column('useremail')
    # ### end Alembic commands ###
