"""true_multi_tenant_scoping

Revision ID: 832efc0a17e4
Revises: 5b0ab702db53
Create Date: 2026-05-20 11:50:18.477400

"""
# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832efc0a17e4'
down_revision = '5b0ab702db53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_school_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', 'start_date', name='_user_school_start_uc')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('class_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('class_test_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classfeestructure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classsubjectassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('enrollment_sequences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('feetypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('grade_scale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('holiday_calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('org_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_test_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('studentfees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('studentsubjectassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test_attendance_months', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('testtype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_branch_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['default_branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'schools', ['default_school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('weekly_off_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    # ----------------------------------------------------
    # DATA MIGRATION: Backfill school_id and branch_id for existing records
    # ----------------------------------------------------
    op.execute("INSERT INTO schools (school_name, is_active, created_at, updated_at) SELECT 'AMS HighSchool', 1, NOW(), NOW() FROM (SELECT 1) AS tmp WHERE NOT EXISTS (SELECT 1 FROM schools LIMIT 1)")
    op.execute("UPDATE branches SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE students s JOIN branches b ON LOWER(s.branch) = LOWER(b.branch_name) SET s.branch_id = b.id, s.school_id = b.school_id WHERE s.branch_id IS NULL")
    op.execute("UPDATE students s JOIN branches b ON s.branch_id = b.id SET s.school_id = b.school_id WHERE s.school_id IS NULL")
    op.execute("UPDATE audit_logs SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE users u JOIN branches b ON LOWER(u.branch) = LOWER(b.branch_name) SET u.default_branch_id = b.id, u.default_school_id = b.school_id WHERE u.default_branch_id IS NULL")
    op.execute("UPDATE users SET default_school_id = (SELECT id FROM schools LIMIT 1) WHERE default_school_id IS NULL")
    op.execute("UPDATE users SET default_branch_id = (SELECT id FROM branches LIMIT 1) WHERE default_branch_id IS NULL AND default_school_id IS NOT NULL")
    op.execute("INSERT INTO user_school_access (user_id, school_id, start_date, is_active, created_at, updated_at) SELECT user_id, default_school_id, '2026-01-01', 1, NOW(), NOW() FROM users u WHERE u.default_school_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM user_school_access usa WHERE usa.user_id = u.user_id AND usa.school_id = u.default_school_id)")
    op.execute("INSERT INTO user_branch_access (user_id, branch_id, school_id, start_date, is_active, created_at, updated_at) SELECT user_id, default_branch_id, default_school_id, '2026-01-01', 1, NOW(), NOW() FROM users u WHERE u.default_branch_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM user_branch_access uba WHERE uba.user_id = u.user_id AND uba.branch_id = u.default_branch_id)")
    op.execute("UPDATE classes c JOIN branches b ON LOWER(c.branch) = LOWER(b.branch_name) SET c.branch_id = b.id, c.school_id = b.school_id WHERE c.branch_id IS NULL")
    op.execute("UPDATE classes SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE class_sections cs JOIN branches b ON cs.branch_id = b.id SET cs.school_id = b.school_id WHERE cs.school_id IS NULL")
    op.execute("UPDATE class_sections SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE roles SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE permissions SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE role_permissions SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE feetypes SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE studentfees sf JOIN students s ON sf.student_id = s.student_id SET sf.branch_id = s.branch_id, sf.school_id = s.school_id WHERE sf.branch_id IS NULL OR sf.school_id IS NULL")
    op.execute("UPDATE classfeestructure cfs JOIN branches b ON LOWER(cfs.branch) = LOWER(b.branch_name) SET cfs.branch_id = b.id, cfs.school_id = b.school_id WHERE cfs.branch_id IS NULL OR cfs.school_id IS NULL")
    op.execute("UPDATE concessions c JOIN branches b ON LOWER(c.branch) = LOWER(b.branch_name) SET c.branch_id = b.id, c.school_id = b.school_id WHERE c.branch_id IS NULL OR c.school_id IS NULL")
    op.execute("UPDATE fee_installments fi JOIN branches b ON LOWER(fi.branch) = LOWER(b.branch_name) SET fi.branch_id = b.id, fi.school_id = b.school_id WHERE fi.branch_id IS NULL OR fi.school_id IS NULL")
    op.execute("UPDATE fee_payments fp JOIN students s ON fp.student_id = s.student_id SET fp.branch_id = s.branch_id, fp.school_id = s.school_id WHERE fp.branch_id IS NULL OR fp.school_id IS NULL")
    op.execute("UPDATE org_master SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE enrollment_sequences es JOIN branches b ON es.branch_id = b.id SET es.school_id = b.school_id WHERE es.school_id IS NULL")
    op.execute("UPDATE student_academic_records sar JOIN students s ON sar.student_id = s.student_id SET sar.branch_id = s.branch_id, sar.school_id = s.school_id WHERE sar.branch_id IS NULL OR sar.school_id IS NULL")
    op.execute("UPDATE attendance a JOIN students s ON a.student_id = s.student_id SET a.branch_id = s.branch_id, a.school_id = s.school_id WHERE a.branch_id IS NULL OR a.school_id IS NULL")
    op.execute("UPDATE weekly_off_rule wor JOIN branches b ON wor.branch_id = b.id SET wor.school_id = b.school_id WHERE wor.school_id IS NULL")
    op.execute("UPDATE holiday_calendar hc JOIN branches b ON hc.branch_id = b.id SET hc.school_id = b.school_id WHERE hc.school_id IS NULL")
    op.execute("UPDATE subjectmaster SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE classsubjectassignment csa JOIN branches b ON csa.branch_id = b.id SET csa.school_id = b.school_id WHERE csa.school_id IS NULL")
    op.execute("UPDATE studentsubjectassignment ssa JOIN students s ON ssa.student_id = s.student_id SET ssa.branch_id = s.branch_id, ssa.school_id = s.school_id WHERE ssa.branch_id IS NULL OR ssa.school_id IS NULL")
    op.execute("UPDATE testtype tt JOIN branches b ON tt.branch_id = b.id SET tt.school_id = b.school_id WHERE tt.school_id IS NULL")
    op.execute("UPDATE test_attendance_months tam JOIN branches b ON tam.branch_id = b.id SET tam.school_id = b.school_id WHERE tam.school_id IS NULL")
    op.execute("UPDATE class_test ct JOIN branches b ON ct.branch_id = b.id SET ct.school_id = b.school_id WHERE ct.school_id IS NULL")
    op.execute("UPDATE class_test_subjects cts JOIN class_test ct ON cts.class_test_id = ct.id SET cts.branch_id = ct.branch_id, cts.school_id = ct.school_id WHERE cts.branch_id IS NULL OR cts.school_id IS NULL")
    op.execute("UPDATE student_test_assignments sta JOIN students s ON sta.student_id = s.student_id SET sta.branch_id = s.branch_id, sta.school_id = s.school_id WHERE sta.branch_id IS NULL OR sta.school_id IS NULL")
    op.execute("UPDATE grade_scales gs JOIN branches b ON gs.branch_id = b.id SET gs.school_id = b.school_id WHERE gs.school_id IS NULL")
    op.execute("UPDATE grade_scale_details gsd JOIN grade_scales gs ON gsd.grade_scale_id = gs.id SET gsd.branch_id = gs.branch_id, gsd.school_id = gs.school_id WHERE gsd.branch_id IS NULL OR gsd.school_id IS NULL")
    op.execute("UPDATE student_marks sm JOIN students s ON sm.student_id = s.student_id SET sm.branch_id = s.branch_id, sm.school_id = s.school_id WHERE sm.branch_id IS NULL OR sm.school_id IS NULL")
    op.execute("UPDATE document_types SET school_id = (SELECT id FROM schools LIMIT 1) WHERE school_id IS NULL")
    op.execute("UPDATE student_documents sd JOIN students s ON sd.student_id = s.student_id SET sd.branch_id = s.branch_id, sd.school_id = s.school_id WHERE sd.branch_id IS NULL OR sd.school_id IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_off_rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_branch_id')
        batch_op.drop_column('default_school_id')

    with op.batch_alter_table('user_branch_access', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('testtype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('test_attendance_months', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('studentsubjectassignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('studentfees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student_test_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student_marks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student_academic_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('org_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('holiday_calendar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('grade_scale_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('feetypes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('enrollment_sequences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('classsubjectassignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('classfeestructure', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('class_test_subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('class_sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')
        batch_op.drop_column('branch_id')

    op.drop_table('user_school_access')
    # ### end Alembic commands ###
