"""Added HR and Attendance modules

Revision ID: af300d750a55
Revises: 1a91df357c35
Create Date: 2026-06-25 13:59:10.512527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af300d750a55'
down_revision = '1a91df357c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code')
    )
    op.create_table('designation_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('designation_code', sa.String(length=50), nullable=False),
    sa.Column('designation_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designation_code')
    )
    op.create_table('shift_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_code', sa.String(length=50), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_in_minutes', sa.Integer(), nullable=True),
    sa.Column('grace_out_minutes', sa.Integer(), nullable=True),
    sa.Column('minimum_working_minutes', sa.Integer(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('is_night_shift', sa.Boolean(), nullable=True),
    sa.Column('allow_overtime', sa.Boolean(), nullable=True),
    sa.Column('late_after_grace', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_code')
    )
    op.create_table('staff_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('default_shift_id', sa.Integer(), nullable=True),
    sa.Column('reporting_manager_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('confirmation_date', sa.Date(), nullable=True),
    sa.Column('relieving_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('PERMANENT', 'CONTRACT', 'TEMPORARY', 'INTERN', 'PART_TIME'), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'PROBATION', 'NOTICE_PERIOD', 'RESIGNED', 'TERMINATED', 'RETIRED'), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('attendance_source', sa.Enum('BIOMETRIC', 'MOBILE', 'WEB', 'MANUAL'), nullable=True),
    sa.Column('weekly_off', sa.String(length=50), nullable=True),
    sa.Column('joining_branch', sa.String(length=100), nullable=True),
    sa.Column('attendance_required', sa.Boolean(), nullable=True),
    sa.Column('payroll_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['default_shift_id'], ['shift_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designation_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['staff_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('attendance_head',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('first_in', sa.DateTime(), nullable=True),
    sa.Column('last_out', sa.DateTime(), nullable=True),
    sa.Column('working_minutes', sa.Integer(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('early_exit_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE', 'HOLIDAY', 'WEEK_OFF'), nullable=True),
    sa.Column('generated_from', sa.Enum('BIOMETRIC', 'MANUAL', 'MOBILE'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('payroll_locked', sa.Boolean(), nullable=True),
    sa.Column('attendance_locked', sa.Boolean(), nullable=True),
    sa.Column('payroll_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_device_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('communication_type', sa.Enum('API', 'TCP_IP', 'CLOUD'), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code')
    )
    op.create_table('attendance_detail',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attendance_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('punch_datetime', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT'), nullable=False),
    sa.Column('verification_mode', sa.Enum('FINGER', 'FACE', 'CARD', 'PIN'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_head.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_device_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_punch_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('biometric_id', sa.String(length=50), nullable=True),
    sa.Column('punch_datetime', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', 'UNKNOWN'), nullable=True),
    sa.Column('verification_mode', sa.Enum('FINGER', 'FACE', 'CARD', 'PIN', 'PALM'), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_device_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_biometric_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('biometric_id', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('face_registered', sa.Boolean(), nullable=True),
    sa.Column('finger_registered', sa.Boolean(), nullable=True),
    sa.Column('pin_registered', sa.Boolean(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_device_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_master', ['staff_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff_id')



    op.drop_table('staff_biometric_mapping')
    op.drop_table('biometric_punch_log')
    op.drop_table('attendance_detail')
    op.drop_table('biometric_device_master')
    op.drop_table('attendance_head')
    op.drop_table('staff_master')
    op.drop_table('shift_master')
    op.drop_table('designation_master')
    op.drop_table('department_master')
    # ### end Alembic commands ###
