"""Add tenant constraints to FeeType and Concession

Revision ID: af6528073d91
Revises: 832efc0a17e4
Create Date: 2026-05-21 11:11:11.057483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6528073d91'
down_revision = '832efc0a17e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_concession_title_branch_year_feetype', ['title', 'branch', 'academic_year', 'fee_type_id'])

    with op.batch_alter_table('feetypes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_feetype_branch_year_school', ['feetype', 'branch', 'academic_year', 'school_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feetypes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_feetype_branch_year_school', type_='unique')

    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_concession_title_branch_year_feetype', type_='unique')

    # ### end Alembic commands ###
