"""add attempts

Revision ID: b0a4f124c7e1
Revises: cc2a2a5a3644
Create Date: 2026-03-11 14:55:36.517801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a4f124c7e1'
down_revision = 'cc2a2a5a3644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        # Add column with a server default so existing rows get 0
        batch_op.add_column(
            sa.Column(
                'attempts',
                sa.Integer(),
                nullable=True,
                server_default='0',
            )
        )
    # Backfill any existing NULLs defensively (in case of partial migrations)
    op.execute(
        "UPDATE password_reset_otps SET attempts = 0 WHERE attempts IS NULL"
    )
    # Enforce NOT NULL to match the model definition
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.alter_column(
            'attempts',
            existing_type=sa.Integer(),
            nullable=False,
            existing_server_default='0',
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
