"""Update Biometric models for enterprise architecture

Revision ID: b1825503a71b
Revises: 2e590438fab3
Create Date: 2026-06-29 14:34:26.363784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1825503a71b'
down_revision = '2e590438fab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_device_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communication_password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sync_mode', sa.Enum('AUTO', 'MANUAL'), nullable=True))
        batch_op.add_column(sa.Column('sync_interval_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_punch', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('firmware_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.Enum('SUCCESS', 'FAILED', 'PENDING'), nullable=True))
        batch_op.add_column(sa.Column('last_successful_sync', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pending_punches', sa.Integer(), nullable=True))

    with op.batch_alter_table('biometric_punch_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_packet', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('received_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('received_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packet_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ack_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(
            'uq_biometric_punch',
            ['device_id', 'biometric_id', 'punch_datetime', 'verification_mode']
        )
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('biometric_punch_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_biometric_punch', type_='unique')
        batch_op.drop_column('processing_error')
        batch_op.drop_column('ack_sent')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('packet_version')
        batch_op.drop_column('received_port')
        batch_op.drop_column('received_ip')
        batch_op.drop_column('raw_packet')

    with op.batch_alter_table('biometric_device_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('pending_punches')
        batch_op.drop_column('last_successful_sync')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('firmware_version')
        batch_op.drop_column('last_punch')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('sync_interval_minutes')
        batch_op.drop_column('sync_mode')
        batch_op.drop_column('communication_password')

    # ### end Alembic commands ###
