"""widen_concession_percentage_to_numeric_10_2

Revision ID: bab7d856c7d9
Revises: b0a4f124c7e1
Create Date: 2026-04-01 11:10:49.941233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bab7d856c7d9'
down_revision = 'b0a4f124c7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.alter_column('percentage',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.alter_column('percentage',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
