"""add employee_id to attendancehead

Revision ID: c54e9ca2846f
Revises: 117244f476ce
Create Date: 2026-07-03 15:44:05.582186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c54e9ca2846f'
down_revision = '117244f476ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_head', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_head', schema=None) as batch_op:
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
