"""making useremail unique

Revision ID: cc2a2a5a3644
Revises: 41858bc61208
Create Date: 2026-03-11 14:24:03.655639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2a2a5a3644'
down_revision = '41858bc61208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_useremail', ['useremail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_useremail', type_='unique')

    # ### end Alembic commands ###
