from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'cdda20559d39'
down_revision = 'af300d750a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'staff_category_master',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('category_code', sa.String(length=20), nullable=False),
        sa.Column('category_name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.user_id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.user_id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('category_code')
    )

    op.create_table(
        'staff_status_master',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status_code', sa.String(length=30), nullable=False),
        sa.Column('status_name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.user_id']),
        sa.ForeignKeyConstraint(['updated_by'], ['users.user_id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('status_code')
    )

    # -------------------------------------------------------
    # SEED DATA
    # -------------------------------------------------------
    now = datetime.utcnow()

    op.bulk_insert(
        sa.table(
            'staff_category_master',
            sa.column('category_code', sa.String),
            sa.column('category_name', sa.String),
            sa.column('display_order', sa.Integer),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                'category_code': 'TEACH',
                'category_name': 'Teaching',
                'display_order': 1,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'category_code': 'NTEACH',
                'category_name': 'Non Teaching',
                'display_order': 2,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'category_code': 'MENIAL',
                'category_name': 'Menial',
                'display_order': 3,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'category_code': 'ADMIN',
                'category_name': 'Administration',
                'display_order': 4,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'category_code': 'MGMT',
                'category_name': 'Management',
                'display_order': 5,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
        ]
    )

    op.bulk_insert(
        sa.table(
            'staff_status_master',
            sa.column('status_code', sa.String),
            sa.column('status_name', sa.String),
            sa.column('display_order', sa.Integer),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                'status_code': 'ACTIVE',
                'status_name': 'Active',
                'display_order': 1,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'status_code': 'PROBATION',
                'status_name': 'Probation',
                'display_order': 2,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'status_code': 'NOTICE_PERIOD',
                'status_name': 'Notice Period',
                'display_order': 3,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'status_code': 'SUSPENDED',
                'status_name': 'Suspended',
                'display_order': 4,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'status_code': 'RESIGNED',
                'status_name': 'Resigned',
                'display_order': 5,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'status_code': 'TERMINATED',
                'status_name': 'Terminated',
                'display_order': 6,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'status_code': 'RETIRED',
                'status_name': 'Retired',
                'display_order': 7,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
        ]
    )

    # Keep the rest of your migration exactly as it is...