"""hr_master_tables_employee_code_redesign

Revision ID: cdda20559d39
Revises: af300d750a55
Create Date: 2026-06-25 16:14:28.844582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdda20559d39'
down_revision = 'af300d750a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_category_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('staff_status_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_code')
    )

    # -------------------------------------------------------
    # SEED: staff_category_master
    # HR Classification — Teaching, Non-Teaching, Menial, etc.
    # -------------------------------------------------------
    now = sa.func.now()
    op.bulk_insert(
        sa.table(
            'staff_category_master',
            sa.column('category_code', sa.String),
            sa.column('category_name', sa.String),
            sa.column('display_order', sa.Integer),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {'category_code': 'TEACH',   'category_name': 'Teaching',        'display_order': 1, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'category_code': 'NTEACH',  'category_name': 'Non Teaching',    'display_order': 2, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'category_code': 'MENIAL',  'category_name': 'Menial',          'display_order': 3, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'category_code': 'ADMIN',   'category_name': 'Administration',  'display_order': 4, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'category_code': 'MGMT',    'category_name': 'Management',      'display_order': 5, 'is_active': True, 'created_at': now, 'updated_at': now},
        ]
    )

    # -------------------------------------------------------
    # SEED: staff_status_master
    # Employment Status — Active, Probation, Notice Period, etc.
    # -------------------------------------------------------
    op.bulk_insert(
        sa.table(
            'staff_status_master',
            sa.column('status_code', sa.String),
            sa.column('status_name', sa.String),
            sa.column('display_order', sa.Integer),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {'status_code': 'ACTIVE',        'status_name': 'Active',        'display_order': 1, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'status_code': 'PROBATION',     'status_name': 'Probation',     'display_order': 2, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'status_code': 'NOTICE_PERIOD', 'status_name': 'Notice Period', 'display_order': 3, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'status_code': 'SUSPENDED',     'status_name': 'Suspended',     'display_order': 4, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'status_code': 'RESIGNED',      'status_name': 'Resigned',      'display_order': 5, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'status_code': 'TERMINATED',    'status_name': 'Terminated',    'display_order': 6, 'is_active': True, 'created_at': now, 'updated_at': now},
            {'status_code': 'RETIRED',       'status_name': 'Retired',       'display_order': 7, 'is_active': True, 'created_at': now, 'updated_at': now},
        ]
    )

    with op.batch_alter_table('department_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_short_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('department_numeric_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('staff_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_status_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_sequence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('biometric_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_staff_master_biometric_id'), ['biometric_id'], unique=False)
        batch_op.create_foreign_key(None, 'staff_category_master', ['staff_category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'staff_status_master', ['staff_status_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default='1' ensures existing rows get TRUE for is_first_login = False (they are established accounts)
        batch_op.add_column(sa.Column('is_first_login', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('failed_login_count')
        batch_op.drop_column('last_login')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('is_first_login')

    with op.batch_alter_table('staff_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_staff_master_biometric_id'))
        batch_op.drop_column('biometric_id')
        batch_op.drop_column('employee_sequence')
        batch_op.drop_column('staff_status_id')
        batch_op.drop_column('staff_category_id')

    with op.batch_alter_table('department_master', schema=None) as batch_op:
        batch_op.drop_column('department_numeric_code')
        batch_op.drop_column('department_short_code')

    op.drop_table('staff_status_master')
    op.drop_table('staff_category_master')
    # ### end Alembic commands ###
