"""add remittance bank fields

Revision ID: dcce7f1ee3f6
Revises: 1092cc5b7f20
Create Date: 2026-09-29 11:55:16.120386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcce7f1ee3f6'
down_revision = '1092cc5b7f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('api_token'), table_name='branch_sync_agent')
    op.drop_table('branch_sync_agent')
    op.drop_index(op.f('uq_biometric_mapping_device_biometric'), table_name='staff_biometric_mapping')
    op.drop_index(op.f('uq_biometric_mapping_staff_device'), table_name='staff_biometric_mapping')
    op.drop_table('staff_biometric_mapping')
    op.add_column('attendance_head', sa.Column('source', sa.Enum('PAYTIME', 'MANUAL', 'MOBILE_APP', 'IMPORT', 'API'), nullable=True))
    op.drop_column('attendance_head', 'generated_from')
    op.alter_column('attendance_staging', 'first_in',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('attendance_staging', 'last_out',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
    op.drop_constraint(op.f('attendance_staging_ibfk_1'), 'attendance_staging', type_='foreignkey')
    op.drop_column('attendance_staging', 'branch_id')
    op.drop_column('biometric_device_master', 'last_sync_at')
    op.drop_column('biometric_punch_log', 'raw_data')
    op.create_foreign_key(None, 'employee_id_sequences', 'users', ['updated_by'], ['user_id'])
    op.create_foreign_key(None, 'employee_id_sequences', 'users', ['created_by'], ['user_id'])
    op.alter_column('petty_cash', 'approved_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'petty_cash', 'users', ['approved_by'], ['user_id'])
    op.add_column('remittance_master', sa.Column('deposit_type', sa.String(length=50), nullable=True))
    op.add_column('remittance_master', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('remittance_master', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('remittance_master', sa.Column('reference_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remittance_master', 'reference_no')
    op.drop_column('remittance_master', 'account_number')
    op.drop_column('remittance_master', 'bank_name')
    op.drop_column('remittance_master', 'deposit_type')
    op.drop_constraint(None, 'petty_cash', type_='foreignkey')
    op.alter_column('petty_cash', 'approved_by',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'employee_id_sequences', type_='foreignkey')
    op.drop_constraint(None, 'employee_id_sequences', type_='foreignkey')
    op.add_column('biometric_punch_log', sa.Column('raw_data', mysql.JSON(), nullable=True))
    op.add_column('biometric_device_master', sa.Column('last_sync_at', mysql.DATETIME(), nullable=True))
    op.add_column('attendance_staging', sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('attendance_staging_ibfk_1'), 'attendance_staging', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendance_staging', 'last_out',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('attendance_staging', 'first_in',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.add_column('attendance_head', sa.Column('generated_from', mysql.ENUM('BIOMETRIC', 'MANUAL', 'MOBILE'), nullable=True))
    op.drop_column('attendance_head', 'source')
    op.create_table('staff_biometric_mapping',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('biometric_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('card_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('face_registered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('finger_registered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('pin_registered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('staff_biometric_mapping_ibfk_1')),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_device_master.id'], name=op.f('staff_biometric_mapping_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_master.id'], name=op.f('staff_biometric_mapping_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('staff_biometric_mapping_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_biometric_mapping_staff_device'), 'staff_biometric_mapping', ['staff_id', 'device_id'], unique=True)
    op.create_index(op.f('uq_biometric_mapping_device_biometric'), 'staff_biometric_mapping', ['device_id', 'biometric_id'], unique=True)
    op.create_table('branch_sync_agent',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('api_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_seen', mysql.DATETIME(), nullable=True),
    sa.Column('last_ip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('heartbeat', mysql.DATETIME(), nullable=True),
    sa.Column('agent_version', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_success_response', mysql.TEXT(), nullable=True),
    sa.Column('last_sync_status', mysql.ENUM('SUCCESS', 'FAILED', 'PENDING'), nullable=True),
    sa.Column('last_error', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('branch_sync_agent_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('branch_sync_agent_ibfk_2')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], name=op.f('branch_sync_agent_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('api_token'), 'branch_sync_agent', ['api_token'], unique=True)
    # ### end Alembic commands ###
