"""add branch_id fk to all core tables

Revision ID: e095f12ddfde
Revises: 64c7627cad58
Create Date: 2026-05-04 14:26:04.863451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e095f12ddfde'
down_revision = '64c7627cad58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classfeestructure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classsubjectassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_classsubject_context'), type_='unique')
        batch_op.create_unique_constraint('uq_classsubject_context', ['class_id', 'subject_id', 'academic_year', 'location_name', 'branch_id'])
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('branch_name')

    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('feetypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_test_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('studentsubjectassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('test_attendance_months', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attendance_months', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('studentsubjectassignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('student_test_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('feetypes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('fee_installments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('concessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('classsubjectassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_classsubject_context', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_classsubject_context'), ['class_id', 'subject_id', 'academic_year', 'location_name', 'branch_name'])
        batch_op.drop_column('branch_id')
        batch_op.drop_column('branch')

    with op.batch_alter_table('classfeestructure', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
