"""add centralized audit_logs table

Revision ID: eaeb2cc7c9ed
Revises: dd8409c802d3
Create Date: 2026-03-02 15:35:20.907578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaeb2cc7c9ed'
down_revision = 'dd8409c802d3'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column('table_name', sa.String(length=100), nullable=False),
        sa.Column('record_id', sa.String(length=100), nullable=True),
        sa.Column('action', sa.String(length=10), nullable=False),
        sa.Column('old_data', sa.JSON(), nullable=True),
        sa.Column('new_data', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
    )

    # Indexes for performance
    op.create_index(
        'idx_audit_table_record',
        'audit_logs',
        ['table_name', 'record_id']
    )

    op.create_index(
        'idx_audit_user',
        'audit_logs',
        ['user_id']
    )

    op.create_index(
        'idx_audit_timestamp',
        'audit_logs',
        ['timestamp']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_table_record', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
