"""Add class_id to grade_scales

Revision ID: eaf76f101918
Revises: 7637bfe41e51
Create Date: 2026-08-19 17:12:05.800370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaf76f101918'
down_revision = '7637bfe41e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_scales', sa.Column('class_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_grade_scale_context'), 'grade_scales', type_='unique')
    op.create_unique_constraint('uq_grade_scale_context', 'grade_scales', ['academic_year', 'branch', 'class_id', 'total_marks'])
    op.create_foreign_key(None, 'grade_scales', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade_scales', type_='foreignkey')
    op.drop_constraint('uq_grade_scale_context', 'grade_scales', type_='unique')
    op.create_unique_constraint(op.f('uq_grade_scale_context'), 'grade_scales', ['scale_name', 'academic_year', 'branch', 'total_marks'])
    op.drop_column('grade_scales', 'class_id')
    # ### end Alembic commands ###
