"""add petty cash tables

Revision ID: fd466747caa0
Revises: 6a53ec797765
Create Date: 2026-06-08 14:37:24.237036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd466747caa0'
down_revision = '6a53ec797765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('ledger_type', sa.Enum('Direct', 'Indirect'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petty_cash',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('voucher_name', sa.String(length=255), nullable=False),
    sa.Column('voucher_type', sa.Enum('Payment', 'Received'), nullable=False),
    sa.Column('ledger_id', sa.BigInteger(), nullable=False),
    sa.Column('paid_to', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('Cash', 'UPI'), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['petty_cash_ledger.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.create_index('idx_petty_cash_branch_year', ['branch_id', 'academic_year'], unique=False)
        batch_op.create_index('idx_petty_cash_date', ['transaction_date'], unique=False)

    op.create_table('petty_cash_voucher_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('petty_cash_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['petty_cash_id'], ['petty_cash.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petty_cash_voucher_items')
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.drop_index('idx_petty_cash_date')
        batch_op.drop_index('idx_petty_cash_branch_year')

    op.drop_table('petty_cash')
    op.drop_table('petty_cash_ledger')
    # ### end Alembic commands ###
